# config
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

# keybinding
set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "[INFO] config reloaded"

unbind %
unbind '"'
bind -r | split-window -h
bind -r - split-window

bind-key f display-popup -E "tmux list-panes -a -F '#{session_name}:#{window_index}.#{pane_index}\t[#{session_name}] [#{window_name}] #{pane_title}' \
  | fzf --prompt='tmux> ' --delimiter='\t' --with-nth=2.. \
        --bind 'enter:become(tmux switch-client -t {1})'"

# plugins
set -g @plugin "tmux-plugins/tpm"

# color scheme
set -g @plugin "rose-pine/tmux"
set -g @rose_pine_variant "main"

# neovim integration
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @smart-splits_no_wrap "" # to disable wrapping. (any value disables wrapping)
set -g @smart-splits_move_up_key    "C-k"
set -g @smart-splits_move_down_key  "C-j"
set -g @smart-splits_move_left_key  "C-h"
set -g @smart-splits_move_right_key "C-l"
set -g @smart-splits_resize_up_key    "C-Up"
set -g @smart-splits_resize_down_key  "C-Down"
set -g @smart-splits_resize_left_key  "C-Left"
set -g @smart-splits_resize_right_key "C-Right"
set -g @smart-splits_resize_step_size "2"

# persistent session
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

# tpm
run "~/.local/share/tmux/plugins/tpm/tpm"
