# Startup
exec-once = /home/miRceLzeS/.config/hypr/scripts/xdg.fish

# Input Method
exec-once = fcitx5

# Notification
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = dunst

# clip board
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
